FROM docker.io/snowdreamtech/frpc:0.68-alpine

COPY --chmod=444 frpc.toml /etc/frp/frpc.toml

LABEL   org.opencontainers.image.title="CubeServices FRPC" \
        org.opencontainers.image.description="Fast reverse proxy client" \
        org.opencontainers.image.source="https://git.thomasaldrian.net/thomasj/cube-services" \
        org.opencontainers.image.authors="Thomas Aldrian <aldrian.thom@proton.me>"
