FROM ghcr.io/lennart-k/rustical:0.14.0

COPY config.toml /etc/rustical/config.toml

LABEL   org.opencontainers.image.title="CubeServices rustical" \
        org.opencontainers.image.description="CalDAV/CardDAV server" \
        org.opencontainers.image.source="https://git.thomasaldrian.net/thomasj/cube-services" \
        org.opencontainers.image.authors="Thomas Aldrian <aldrian.thom@proton.me>"
