# Headers common to all
[http.middlewares.sec-headers-all.headers]
  browserXssFilter = true
  # accesscontrolallowmethods = "GET, HEAD, POST"
  contentTypeNosniff = true
  customFrameOptionsValue = "SAMEORIGIN"
  forceSTSHeader = true
  referrerPolicy = "same-origin"
  sslRedirect = true
  stsIncludeSubdomains = true
  stsPreload = true
  stsSeconds = 31536000
  # [http.middlewares.sec-headers.headers.customResponseHeaders]
  #   X-Robots-Tag = "none,nofollow,noindex,noarchive,nosnippet,notranslate,noimageindex"

# Relaxed CSP for services which need it
[http.middlewares.csp-relaxed.headers]
  contentSecurityPolicy = """
      default-src 'self'; \
      base-uri 'self'; \
      connect-src 'self' wss: https:; \
      frame-src 'self'; \
      script-src 'self' 'unsafe-inline' 'unsafe-eval'; \
      style-src 'self' 'unsafe-inline'; \
      font-src 'self' data:; \
      img-src 'self' data: https: blob:; \
      frame-ancestors 'self'; \
      form-action 'self'; \
      object-src 'none'; \
      upgrade-insecure-requests; \
    """

# Strict(er) CSP should be preferred
[http.middlewares.csp-default.headers]
  contentSecurityPolicy = """
      default-src 'self'; \
      base-uri 'self'; \
      connect-src 'self'; \
      frame-src 'self'; \
      script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; \
      style-src 'self' 'unsafe-inline'; \
      font-src 'self' data:; \
      img-src 'self' https://*.thomasaldrian.net data:; \
      frame-ancestors 'self'; \
      form-action 'self'; \
      object-src 'none'; \
      upgrade-insecure-requests; \
    """
