[http.middlewares.wellknown-security-txt.plugin.security-txt]
  contact = ["mailto://admin@thomasaldrian.net", "mailto://aldrian.thom@proton.me"]
  encryption = "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa63f6ab8437c8403bb7d82d83ca828143aa1dd2c"
  expires = "2026-11-01T00:00:00.000Z"
  preferredLanguages = "en, de"
