# note: never use the :latest tag in a production site
FROM docker.io/library/caddy:2

COPY Caddyfile /etc/caddy/Caddyfile

LABEL   org.opencontainers.image.title="CubeServices InvenTree proxy" \
        org.opencontainers.image.desciption="Caddy proxy for InvenTree inventory management system" \
        org.opencontainers.image.source="https://git.thomasaldrian.net/thomasj/cube-services" \
        org.opencontainers.image.authors="Thomas Aldrian <aldrian.thom@proton.me>"
