# note: never use the :latest tag in a production site
ARG UPSTREAM_VERSION=2
FROM docker.io/library/caddy:${UPSTREAM_VERSION}

COPY Caddyfile /etc/caddy/Caddyfile

LABEL   org.opencontainers.image.title="CubeServices InvenTree proxy" \
        org.opencontainers.image.description="Caddy proxy for InvenTree inventory management system" \
        org.opencontainers.image.source="https://git.thomasaldrian.net/thomasj/cube-services" \
        org.opencontainers.image.authors="Thomas Aldrian <aldrian.thom@proton.me>"
