FROM docker.io/library/traefik:v3.7.5

RUN mkdir -p /etc/traefik/dynamic
COPY traefik.toml /etc/traefik
COPY dynamic/ /etc/traefik/dynamic

LABEL   org.opencontainers.image.title="CubeServices Traefik" \
        org.opencontainers.image.description="A modern reverse-proxy" \
        org.opencontainers.image.source="https://git.thomasaldrian.net/thomasj/cube-services" \
        org.opencontainers.image.authors="Thomas Aldrian <aldrian.thom@proton.me>"
