[log]
  level = "INFO"


[entryPoints]

  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      scheme = "https"
      to = ":443"

  [entryPoints.websecure]
    address = ":443"
    asDefault = true
    http.middlewares = ["cf-real-ip@file", "sec-headers@file"]
    http.tls.certResolver = "le"
    proxyProtocol.trustedIPs = ["10.99.0.0/28"]

  # Socket only
  [entryPoints.ldapsecure]
  [entryPoints.sshalt]

  # FRP
  [entryPoints.imaps]
    address = ":993"
    proxyProtocol.trustedIPs = ["10.99.0.0/28"]
  [entryPoints.smtp]
    address = ":25"
    proxyProtocol.trustedIPs = ["10.99.0.0/28"]
  [entryPoints.smtps]
    address = ":465"
    proxyProtocol.trustedIPs = ["10.99.0.0/28"]


[providers.docker]
  exposedByDefault = false


[certificatesResolvers.le.acme]
  dnsChallenge.provider = "cloudflare"
  email = "aldrian.thom+letsencrypt@proton.me"
  storage = "/letsencrypt/acme.json"


[api]
  disableDashboardAd = true


[ocsp]


# Do not verify certs for kanidm (web UI and ldap) yet
[serversTransport]
  insecureSkipVerify = true


[tcpServersTransport.tls]
  insecureSkipVerify = true


[experimental.plugins]
  [experimental.plugins.traefik-oidc-auth]
    moduleName = "github.com/sevensolutions/traefik-oidc-auth"
    version = "v0.17.0"

  # Yes this is unmaintained, but there's currently no better alternative
  [experimental.plugins.cloudflarewarp]
    moduleName = "github.com/BetterCorp/cloudflarewarp"
    version = "v1.3.3"


[providers.file]
  directory = "/etc/traefik/dynamic/"
