ARG UPSTREAM_VERSION=1.37.2-alpine
FROM ghcr.io/dani-garcia/vaultwarden:${UPSTREAM_VERSION}

COPY vaultwarden.env /.env

LABEL   org.opencontainers.image.title="CubeServices Vaultwarden" \
        org.opencontainers.image.description="Unofficial bitwarden compatible server" \
        org.opencontainers.image.source="https://git.thomasaldrian.net/thomasj/cube-services" \
        org.opencontainers.image.authors="Thomas Aldrian <aldrian.thom@proton.me>"
